version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456AHMED
      - DB_NAME=library_management
    depends_on:
      - db

  db:
    image: mysql:5.7  # Using the official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: 123456AHMED
      MYSQL_DATABASE: library_management
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
